version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # This maps the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

  locust:
    build: .
    command: locust -f locustfile.py --host=http://web:8000
    ports:
      - "8089:8089"
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - .:/app  # This maps the current directory to /app in the container
