version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthcheck"]
      interval: 30s  
      timeout: 10s  
      retries: 5    

  locust:
    build: .
    command: locust -f locustfile.py --host=http://web:8000
    ports:
      - "8089:8089"
    depends_on:
      web:
        condition: service_healthy
